-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "clientes"."VeiculosAtivos_Beneficios" add column "PortfolioPreco_Id" uuid
--  not null;
