-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "operacional"."OrdemDeServico_CheckList" add column "updated_at" timestamptz
--  null default now();
