-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."Combos_Combos" add column "ComboPertencente_Id" uuid
--  not null;
