-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."PrestadoresDeServicos_Produtos_Precos" add column "TipoDePreco_Id" uuid
--  null;
