-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."PrestadoresDeServicos_Produtos_Itens" add column "TipoDeItem_Id" text
--  null;
