-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."Propostas_Servicos" add column "ServicosPreco_Id" uuid
--  not null;
