table:
  name: Configuracoes
  schema: estoque
object_relationships:
  - name: FamiliaChips
    using:
      foreign_key_constraint_on: FamiliaChips_Id
  - name: FamiliaEquipamentos
    using:
      foreign_key_constraint_on: FamiliaEquipamentos_Id
  - name: FamiliaIdentificadores
    using:
      foreign_key_constraint_on: FamiliaIdentificadores_Id
  - name: Item
    using:
      foreign_key_constraint_on: ItemRastreadores_Id
