table:
  name: KitsDeInsumo
  schema: producao
object_relationships:
- name: Item
  using:
    foreign_key_constraint_on: Item_Id
- name: TiposDeKitDeInsumo
  using:
    foreign_key_constraint_on: Tipo_Id
array_relationships:
- name: Itens
  using:
    foreign_key_constraint_on:
      column: KitDeInsumo_Id
      table:
        name: KitDeInsumo_Itens
        schema: producao
- name: KitsDeInstalacao
  using:
    foreign_key_constraint_on:
      column: KitDeInsumo_Id
      table:
        name: KitsDeInstalacao
        schema: producao
event_triggers:
- definition:
    delete:
      columns: "*"
    enable_manual: true
    insert:
      columns: "*"
    update:
      columns:
      - Tipo_Id
      - updated_at
      - deleted_at
      - Id
      - created_at
      - CodigoReferencia
  name: Logs_producao_KitsDeInsumo
  retry_conf:
    interval_sec: 10
    num_retries: 0
    timeout_sec: 60
  webhook: "{{LOGS_EVENT_BASE_URL}}"
