table:
  name: ChipsSituacoes
  schema: producao
is_enum: true
array_relationships:
  - name: Chips
    using:
      foreign_key_constraint_on:
        column: Situacao_Id
        table:
          name: Chips
          schema: producao
