-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."Combos_Precos" add column "ValorDeRecorrencia" float8
--  not null default '0';
