-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "identidades"."Fornecedores" add column "PrestadorDeServico" boolean
--  not null default 'false';
