-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "producao"."KitsDeInsumo" add column "Ativo" boolean
--  not null default 'false';
