-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "clientes"."VeiculosAtivos_Servicos" add column "DataDeDesativacao" timestamptz
--  not null;
