-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."PrestadorDeServicos_Servicos" add column "Valor" float8
--  not null;
