-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."Fornecedores_Produtos_Precos" add column "Fornecedor_Produto_Id" uuid
--  not null;
