-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."Propostas_Produtos" add column "ProdutoPreco_Id" uuid
--  not null;
