-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "propostas"."Propostas" add column "FormaDePagamentoDaAdesao_Id" text
--  null;
