-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."Propostas" add column "Aceito" boolean
--  not null default 'false';
