-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "propostas"."Propostas_Combos" add column "Quantidade" integer
--  not null default '1';
