-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."Servicos_Atributos" add column "Atributo_Id" uuid
--  not null;
