export { getResumeCollection } from './getResumeCollection'
export { getRecurrenceTotalValue } from './getRecurrenceTotalValue'
export { getVehicleCollection } from './getVehicleCollection'
export { createVehicleProposal } from './createVehicleProposal'
export { changeOwnership } from './changeOwnership'
export { changeOwnershipSingle } from './changeOwnershipSingle'
export { changeVehicle } from './changeVehicle'