-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "propostas"."Propostas_RegrasETermosDeUso" add column "Informado" boolean
--  not null default 'false';
