-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "clientes"."VeiculosAtivos_Produtos" add column "VeiculoAtivoPlano_Id" uuid
--  null;
