-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "operacional"."OrdemDeServico_Agendamentos" add column "Endereco" jsonb
--  not null default jsonb_build_array();
