-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."Propostas_Combos" add column "ComboPreco_Id" uuid
--  not null;
