-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "propostas"."Propostas_Veiculos" add column "PossuiGNV" boolean
--  not null default 'false';
