table:
  name: KitsDeInstalacao
  schema: producao
object_relationships:
- name: Item
  using:
    foreign_key_constraint_on: Item_Id
- name: KitDeInsumo
  using:
    foreign_key_constraint_on: KitDeInsumo_Id
- name: Rastreador
  using:
    foreign_key_constraint_on: Rastreador_Id
