-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "operacional"."OrdemDeServico_Agendamentos_Itens" add column "Agendamento_Id" uuid
--  not null;
