-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "comercial"."Acoes" add column "Etapas_Id" jsonb
--  not null default jsonb_build_array();
